### PR TITLE
Added a Python implementation

### PR DESCRIPTION
**Pull request by JanVanRyswyck**

### CODE REVIEW

**Comment by codecop** [comment]
Thank you. I know the Java version has the QuestData but C and Cpp do not have it. I would like to avoid it as the exercise is about Data Clumps first (groups of arguments), and then these become Data Classes (i.e. QuestData) and then these become real objects. All the logic and tests stay the same. We cannot mutate method parameters easily as C and Cpp can so this is a problem. Do you have ideas for that? Is there a "ref" parameter modifier in Python? Should it be a array of one element? (But keep the original code somewhere in case we do not find a good solution for that.)

**Comment by codecop** [comment]
Seems there is no ref parameter in Python, so any workarounds are nasty and probably not idiomatic. So I guess for Python it has to look like you provide it. Please make the following modifications
* port of Main class (now also in Java)
* Github action to run the tests for Python
Thank you.

**Comment by JanVanRyswyck** [comment]
Apologies for not getting back sooner. I've been working on preparing a TDD workshop. I have it on my todo list for later this week, and I'll get back to you.

**Comment by JanVanRyswyck** [comment]
I finally found some time to look into this. Something I tried is to use a dictionary instead of a data class, which makes the code a bit more nasty as well. I come across this all the time when working with legacy code in Python. 

Also added a main function and an actions script. Let me know what you think about these changes.

**Comment by codecop** [comment]
Thank you. Maybe I will use both Python versions, I also have two Java versions...

**Comment by codecop** [comment]
Yes this looks very good. Very true to the original. Awesome.

**Comment by codecop** [comment]
I added the first PR as "Python_dataclass", nice to have different starting points. Thanks again.

**Comment by JanVanRyswyck** [comment]
Thx for accepting the PR.

**Pull request merged**
